### ISSUE TITLE
INRIA word list: Separate out subanta-s?

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/autocomplete-sa-en#2]
Rationale: 
- Better organization and transparency. (Facilitates replacing with better alternatives in the future.)
- For ti~Nanta-s, more reliable forms are available from dhaval.

@avinashvarna - would this be easy for you?

**Comment by avinashvarna** [comment]
Yes, not too difficult. The INRIA db is organized into individual XML files. E.g. see SL_*.xml in dhaval's [inriaxmlwrapper](https://github.com/drdhaval2785/inriawrapper). The simplest I can think of is to convert each xml file into a corresponding csv file. It will then be easier to decide which ones to include. Will that work?

**Comment by vvasuki** [comment]
yes - that's good!

**Comment by avinashvarna** [comment]
Submitted PR #4

**Comment by avinashvarna** [comment]
Can we close this issue then? (I can't)

**Comment by vvasuki** [comment]
Thanks!
